project_name: Kubernetes Node Label Manager
builds:
   - main: ./cmd/nodelabels/main.go
     binary: nodelabels
     env:
        - CGO_ENABLED=0
     goos:
        - linux
        - darwin
        - windows
     goarch:
        - amd64

archives:
   - format: binary
     name_template: "{{ .Binary }}.{{ .Os }}.{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
       - '^docs:'
       - '^doc:'
       - '^test:'

dockers:
   - image_templates:
        - "cycoresystems/nodelabels:{{ .Tag }}"
        - "cycoresystems/nodelabels:v{{ .Major }}"
        - "cycoresystems/nodelabels:v{{ .Major }}.{{ .Minor }}"
        - cycoresystems/nodelabels:latest
