language: go
go:
   - "1.13"
install:
   - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.21.0
   - curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
script: bash check.sh
services:
   - docker
deploy:
   - provider: script
     skip_cleanup: true
     script: bash release.sh
     on:
        tags: true
        condition: $TRAVIS_OS_NAME = linux

