kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-manager
subjects:
  - kind: ServiceAccount
    name: default
    namespace: voip
roleRef:
  kind: ClusterRole
  name: system:controller:node-controller
  apiGroup: rbac.authorization.k8s.io

